[/Script/XmlUI.XmlUISettings]
BaseWidgetClass=/Script/UMG.UserWidget
XmlRootPath=
BakedBlueprintOutputPath=/Game/UI
bStrictValidation=True
; FontFamilyMap=(("FigmaFontName","/Game/Path/To/FontAsset.FontAsset"))
